### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by CrystalShardz** [geoscience-community-codes/tephra2#1]
When attempting to run make as instructed this fails. See output below:

`phil@B88A60FA4E7F:/mnt/c/users/phil/downloads/tephra2-master$ make
cd inversion_src; make; cd ..
make[1]: Entering directory '/mnt/c/users/phil/downloads/tephra2-master/inversion_src'
`which mpicc` -Wall  -O3 -idirafter ../include -c master.c
/bin/sh: 1: -Wall: not found
makefile:38: recipe for target 'master.o' failed
make[1]: *** [master.o] Error 127
make[1]: Leaving directory '/mnt/c/users/phil/downloads/tephra2-master/inversion_src'
cd forward_src; make; cd ..
make[1]: Entering directory '/mnt/c/users/phil/downloads/tephra2-master/forward_src'
`which gcc` -Wall -O3 -idirafter ../include -o tephra2-2012 new_tephra.o tephra2_calc.o -lm ../lib64/libgc.a -ldl
/usr/bin/ld: ../lib64/libgc.a(malloc.o): relocation R_X86_64_32S against symbol `GC_obj_kinds' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib64/libgc.a(mallocx.o): relocation R_X86_64_32S against symbol `GC_obj_kinds' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib64/libgc.a(alloc.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib64/libgc.a(reclaim.o): relocation R_X86_64_32S against undefined symbol `GC_leaked' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib64/libgc.a(allchblk.o): relocation R_X86_64_32S against symbol `GC_hblkfreelist' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib64/libgc.a(misc.o): relocation R_X86_64_32S against undefined symbol `GC_arrays' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib64/libgc.a(os_dep.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib64/libgc.a(mark_rts.o): relocation R_X86_64_32S against undefined symbol `GC_arrays' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib64/libgc.a(headers.o): relocation R_X86_64_32S against undefined symbol `GC_arrays' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib64/libgc.a(mark.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib64/libgc.a(obj_map.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib64/libgc.a(blacklst.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib64/libgc.a(finalize.o): relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib64/libgc.a(new_hblk.o): relocation R_X86_64_32S against symbol `GC_obj_kinds' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib64/libgc.a(dyn_load.o): relocation R_X86_64_32 against symbol `dl_iterate_phdr@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib64/libgc.a(mach_dep.o): relocation R_X86_64_32 against symbol `GC_push_current_stack' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
makefile:29: recipe for target 'tephra2-2012' failed
make[1]: *** [tephra2-2012] Error 1
make[1]: Leaving directory '/mnt/c/users/phil/downloads/tephra2-master/forward_src'

Please can you advise how this can be resolved?
This is running under Ubuntu 18.04.4 LTS

**Comment by ljc-geo** [comment]
Hi,
I received your email. Thank you for bringing this to my attention.

First, let me ask you, do you have a working version of mpi installed. If you are trying to compile and use the inversion portion, this inversion executable needs to compile with 'mpicc' and needs access to the mpi libraries (the dev or devel packages).

Also, since the errors are quite long it would be helpful to capture them to a file and send me the file. When trying to read them, I feel some bits are missing. Could you do this?

Thanks, I will work on getting this to compile.

Cheers,
Laura Connor
Research Associate
813-334-0546 (mobile)

School of Geosciences​
University of South Florida
Tampa, Florida 33620


________________________________

**Comment by CrystalShardz** [comment]
Hi,
Thank you for your response. I have installed the mpi libraries onto my ubuntu machine using the libopenmpi-dev package and receive the same result. I have attached the output as requested.
[make.txt](https://github.com/geoscience-community-codes/tephra2/files/5061797/make.txt)

**Comment by ljc-geo** [comment]
Thank you!
I believe the problem is with the static libraries I compiled ~ five years ago for the memory management. They are out of data and rely on an older version of the c compiler (gcc). These memory management libraries are now available as packages for linux. For ubuntu, you will need to install these two additional packages:

libgc-dev   : a conservative garbage collector for C (development)
libgc1c2  : (this is a dependency and may install automatically with libgc-dev)

In case you need a source: https://ubuntu.pkgs.org/18.04/ubuntu-main-amd64/
Ubuntu 18.04 LTS (Bionic Beaver) - Ubuntu Main amd64<https://ubuntu.pkgs.org/18.04/ubuntu-main-amd64/>
Packages from Ubuntu Main amd64 repository of Ubuntu 18.04 LTS (Bionic Beaver) distribution.
ubuntu.pkgs.org

I will update the makefiles on the gscommunitycodes (tepjhra2)  github site today. I have compiled on my system (opensuse - tumbleweed) without errors so hopefully this will solve  your compiling issues as well on ubuntu

Also, you will need to add openmpi to your environment. Here is some instruction if you need it:

Use the mpi-selector program . Try:
mpi-selector --list

this will tell you which mpi you have. Then:
 mpi-selector --set  xxxx

where xxx is the output from mpi-selector --list

then, the easiest is to log out then log back in to your system so that the changes will be 'sourced' and become part of your environment.

Laura Connor
Research Associate
813-334-0546 (mobile)

School of Geosciences​
University of South Florida
Tampa, Florida 33620


________________________________

**Comment by CrystalShardz** [comment]
Sorry for the delay to update you. I've just re-ran and can now successfully build the project on Ubuntu 👍 There are a few warnings but nothing to worry about. Ran a test using the sample data provided and this outputted correctly. Thank you for sorting so swiftly.

**Comment by ljc-geo** [comment]
No worries 🙂,
I am glad we were able to get things updated and working.

Would you tell me what warnings you received? I did not receive any; maybe this is something i could fix before I close this issue.

Thanks!

Laura Connor
Research Associate
813-334-0546 (mobile)

School of Geosciences​
University of South Florida
Tampa, Florida 33620


________________________________
